name: Generate Waka SVG Badges

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Python script in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e WAKATIME_API_KEY='${{ secrets.WAKATIME_API_KEY }}' \
            python:3.11-slim \
            sh -c "pip install requests && python generate_waka_svg.py"

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/*.svg
          git commit -m "Update WakaTime SVG badges" || echo "No changes"
          git pull origin main --rebase
          git push