name: Generate Waka SVG Badges

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Debug WakaTime Secret
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TOTAL_CODE_TIME: "True"

      - name: Generate SVG badges
        run: |
          echo "WAKATIME_API_KEY=${{ secrets.WAKATIME_API_KEY }}" >> $GITHUB_ENV
          python generate_waka_svg.py
        shell: bash

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/*.svg
          git commit -m "Update WakaTime SVG badges" || echo "No changes"
          git pull origin main --rebase
          git push